backend:
  name: github
  repo: usdasus/Firefly
  branch: main

media_folder: public/images
public_folder: /images

publish_mode: simple

site_url: https://blog.wuyiyan.cc.cd
display_url: https://blog.wuyiyan.cc.cd

collections:
  - name: posts
    label: 文章
    label_singular: 文章

    folder: src/content/posts

    create: true
    delete: true
    extension: md
    format: frontmatter

    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    editor:
      preview: false

    fields:
      - label: 标题
        name: title
        widget: string

      - label: 发布时间
        name: published
        widget: datetime
        format: "YYYY-MM-DD"

      - label: 描述
        name: description
        widget: text
        required: false

      - label: 标签
        name: tags
        widget: list
        required: false

      - label: 分类
        name: category
        widget: string
        required: false

      - label: 草稿
        name: draft
        widget: boolean
        default: false

      - label: 正文
        name: body
        widget: markdown